spring:
  couchbase:
    bootstrap-hosts: http://localhost
    bucket:
      name: users
      password: password
  security:
    basic:
      enable: false
    ignored: /**
  jackson:
    default-property-inclusion: NON_NULL
  main:
    web-application-type: reactive
server:
  compression:
    enabled: true

logging:
  level:
    org.springframework.data.couchbase.repository.query: DEBUG
